collaborare/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('team/', views.team_index, name='team_index'),
    path('team/<int:team_id>/players/', views.team_detail, name='team_detail'),
    path('team/create', views.TeamCreate.as_view(), name='team_create'),
    path('team/players/', views.players_index, name='index'),
    path('team/players/<int:player_id>/', views.players_detail, name='detail'),
    path('team/players/create/', views.PlayerCreate.as_view(), name='players_create'),
    path('team/players/<int:pk>/update/',
         views.PlayerUpdate.as_view(), name='players_update'),
    path('team/players/<int:pk>/delete/',
         views.PlayerDelete.as_view(), name='players_delete'),
    path('team/players/<int:player_id>/add_stats',
         views.add_stats, name='add_stats'),
    # path('players/<int:player_id>/delete_stats/',
    #      views.delete_stats, name='delete_stats'),
    path('training/', views.TrainingList.as_view(), name='training_index'),
    path('training/<int:pk>/', views.TrainingDetail.as_view(),
         name='training_detail'),
    path('training/create/', views.TrainingCreate.as_view(),
         name='training_create'),
    path('training/<int:pk>/update/',
         views.TrainingUpdate.as_view(), name='training_update'),
    path('training/<int:pk>/delete/',
         views.TrainingDelete.as_view(), name='training_delete'),
    path('team/players/<int:player_id>/assoc_training/<int:training_id>/',
         views.assoc_training, name='assoc_training'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.db.models import Sum, Avg, Count
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date


# Create your models here.

POSITIONS = [
    ('GK', 'Goalkeeper'),
    ('DEF', 'Defender'),
    ('MID', 'Midfielder'),
    ('FW', 'Forward'),
]

PREFERRED_FOOT = [
    ('R', 'Right'),
    ('L', 'Left'),
    ('B', 'Both'),
]

DRILLS = [
    ('SQD', 'Team'),
    ('GK', 'Goalkeeping'),
    ('DEF', 'Defending'),
    ('PAS', 'Passing'),
    ('STR', 'Strength'),
    ('FIT', 'Fitness'),
    ('SHO', 'Shooting'),
]


class Team(models.Model):
    name = models.CharField(max_length=80)
    league = models.CharField(max_length=30)
    division = models.CharField(max_length=10)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('team_index', kwargs={'team_id': self.id})


class Training(models.Model):
    drill = models.CharField(
        max_length=3, choices=DRILLS, default=DRILLS[0][0])
    description = models.CharField(max_length=100)
    date = models.DateField(default=date.today)
    duration = models.IntegerField("Duration (minutes)")
    completed = models.BooleanField(default=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.drill} Training, {self.date}"

    def get_absolute_url(self):
        return reverse('training_detail', kwargs={'pk': self.id})


class Player(models.Model):
    first_name = models.CharField('First Name', max_length=100)
    last_name = models.CharField('Last Name', max_length=100)
    age = models.IntegerField()
    kitNumber = models.IntegerField('Kit Number')
    position = models.CharField(
        max_length=3, choices=POSITIONS, default=POSITIONS[0][0])
    preferredFoot = models.CharField(
        'Preferred Foot', max_length=1, choices=PREFERRED_FOOT, default=PREFERRED_FOOT[0][0])
    training = models.ManyToManyField(Training, blank=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.last_name} plays for {self.team.name}"

    class Meta:
        ordering = ['kitNumber']

    def get_absolute_url(self):
        return reverse('detail', kwargs={'player_id': self.id})


class Stat(models.Model):
    goals = models.IntegerField()
    assists = models.IntegerField()
    clean_sheets = models.IntegerField(blank=True, null=True)
    shots = models.IntegerField()
    date = models.DateField("Appearance Date", default=date.today)

    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.player.last_name} scored {self.goals} for {self.player.team.name} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Stat, Team
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class StatForm(ModelForm):
    class Meta:
        model = Stat
        fields = ['date', 'goals', 'assists',
                  'clean_sheets', 'shots']


class SignupForm(UserCreationForm):
    username = forms.CharField(
        max_length=50, required=True, help_text='Required')
    email = forms.EmailField(
        max_length=254, required=True, help_text='Required')
    first_name = forms.CharField(
        max_length=30, required=True, help_text='Required')
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView
from .models import Player, Training, Team
from .forms import StatForm, SignupForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    signupform = SignupForm()
    context = {'signupform': signupform, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def players_index(request):
    players = Player.objects.all()
    return render(request, 'players/index.html', {'players': players})


@login_required
def players_detail(request, player_id):
    player = Player.objects.get(id=player_id)
    training_player_doesnt_have = Training.objects.exclude(
        id__in=player.training.all().values_list('id'))
    stat_form = StatForm()
    return render(request, 'players/detail.html', {'player': player, 'stat_form': stat_form, 'training': training_player_doesnt_have})


@login_required
def team_index(request):
    teams = Team.objects.filter(user=request.user)
    return render(request, 'team/index.html', {'teams': teams})


@login_required
def team_detail(request, team_id):
    team = Team.objects.get(id=team_id)
    players = Player.objects.filter(team=team)
    trainings = Training.objects.filter(team=team)
    return render(request, 'team/detail.html', {'team': team, 'players': players, 'trainings': trainings})


@login_required
def add_stats(request, player_id):
    form = StatForm(request.POST)
    if form.is_valid():
        new_stats = form.save(commit=False)
        new_stats.player_id = player_id
        new_stats.save()
    return redirect('detail', player_id=player_id)


# @login_required
# def team_create(request, user):
#     form = TeamForm(request.POST)
#     if form.is_valid():
#         new_team = form.save(commit=False)
#         user = new_team.user
#         new_team.save()
#     return redirect('team/create.html', user=user)


class TeamCreate(LoginRequiredMixin, CreateView):
    model = Team
    fields = '__all__'
    success_url = '/team/'


class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    fields = ['first_name', 'last_name', 'age', 'kitNumber',
              'position', 'preferredFoot', 'team']


class PlayerUpdate(LoginRequiredMixin, UpdateView):
    model = Player
    fields = '__all__'


class PlayerDelete(LoginRequiredMixin, DeleteView):
    model = Player
    success_url = '/players/'


class TrainingList(LoginRequiredMixin, ListView):
    model = Training


class TrainingDetail(LoginRequiredMixin, DetailView):
    model = Training


class TrainingCreate(LoginRequiredMixin, CreateView):
    model = Training
    fields = '__all__'


class TrainingUpdate(LoginRequiredMixin, UpdateView):
    model = Training
    fields = ['drill', 'date', 'description', 'duration', 'completed', ]


class TrainingDelete(LoginRequiredMixin, DeleteView):
    model = Training
    success_url = '/training/'


@login_required
def assoc_training(request, player_id, training_id):
    Player.objects.get(id=player_id).training.add(training_id)
    return redirect('detail', player_id=player_id)

main_app/templates/players/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class='player-details-header'>Player Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title" id='player-title'>
      <h1>{{ player.last_name }}</h1>
      <h2>Kit Number: {{player.kitNumber}}</h2>
    </span>
    <div class='container-div'>
      <div class="info-div">
        <h3>Age: {{ player.age }}</h3>
        <h3>Position: {{ player.position }}</h3>
        <h3>Preferred Foot: {{ player.preferredFoot }}</h3>
      </div>
      <div class='action-container'>
        <div class="card-action">
          <a href="{% url 'players_update' player.id %}">Edit</a>
          <a href="{% url 'players_delete' player.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="card">
  <form action="{% url 'add_stats' player.id %}" method="post">
    {% csrf_token %}
    {{ stat_form.as_p }}
    <div class='button-div'>
      <input type="submit" class="btn btn-primary" id='btn-primary' value="Add Stat">
    </div>
  </form>
  <div class='stat-table'>
    <table class="table table-striped">
      <thead>
        {% if player.position == 'GK' %}
        <tr>
          <th scope="col">Appearance Date</th>
          <th scope="col">Clean Sheet</th>
        </tr>
        {% else %}
        <tr>
          <th scope="col">Appearance Date</th>
          <th scope="col">Goals</th>
          <th scope="col">Assists</th>
          <th scope="col">Shots</th>
        </tr>
      </thead>
      {% endif %}
      <tbody>
        {% for stat in player.stat_set.all %}
        {% if player.position == 'GK' %}
        <tr>
          <td scope="row">{{stat.date}}</td>
          <td scope="row">{{stat.clean_sheets}}</td>
        </tr>
        {% else %}
        <tr>
          <td scope="row">{{stat.date}}</td>
          <td scope="row">{{stat.goals}}</td>
          <td scope="row">{{stat.assists}}</td>
          <td scope="row">{{stat.shots}}</td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="card">
  <div class="card-content">
    <h3>{{ player.last_name }}'s Training</h3>
    {% if player.training.count %}
    {% for training in player.training.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          {{ training.drill }}
        </span>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>No training scheduled yet</h5>
    {% endif %}
  </div>
  <div class="card">
    <h3>All Scheduled Trainings</h3>
    {% if training.count %}
    {% for training in training.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          {{ training.drill }}
        </span>
      </div>
    </div>
    <div class="card">
      <form action="{% url 'assoc_training' player.id training.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Add</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <h5>{{player.last_name}} is already scheduled for all training drills.</h5>
  {% endif %}
</div>
{% endblock %}

main_app/templates/players/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Player List</h1>

{% for player in players %}

<div class="card">
  <div class="card-content">
    <span class="card-title">
      <a href="{% url 'detail' player.id %}" class="player-title">
        <h2 class='player-name'>{{ player.last_name }} #{{ player.kitNumber}}</h2>
      </a>
    </span>
    <h3>Age: {{ player.age }}</h3>
    <h3>Position: {{ player.position }}</h3>
    <h3>Preferred Foot: {{ player.preferredFoot }}</h3>
  </div>
</div>
{% endfor %}

{% endblock %}